package GUI;

import javax.swing.JFrame;
import java.io.OutputStream;
import java.io.PrintStream;
import gui.CustomOutputStream;
/**
 *
 * @author lavan
 */
public class InterpreterForm extends javax.swing.JFrame {

    /**
     * Creates new form InterpreterForm
     */
    public InterpreterForm() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jlabelCloseWin = new javax.swing.JLabel();
        jLabelMinWindow = new javax.swing.JLabel();
        jlabelCloseWin1 = new javax.swing.JLabel();
        jLabelMinWindow1 = new javax.swing.JLabel();
        jlabelCloseWin2 = new javax.swing.JLabel();
        jLabelMinWindow2 = new javax.swing.JLabel();
        jlabelCloseWin3 = new javax.swing.JLabel();
        jLabelMinWindow3 = new javax.swing.JLabel();
        jLabelTitle = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldDTC = new javax.swing.JTextField();
        jTextFieldMileage = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldVin = new javax.swing.JTextField();
        jButtonEnter = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaDiagnosis = new javax.swing.JTextArea();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jlabelCloseWin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlabelCloseWin.setForeground(new java.awt.Color(250, 250, 250));
        jlabelCloseWin.setText("X");
        jlabelCloseWin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlabelCloseWin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlabelCloseWinMouseClicked(evt);
            }
        });

        jLabelMinWindow.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelMinWindow.setForeground(new java.awt.Color(250, 250, 250));
        jLabelMinWindow.setText("-");
        jLabelMinWindow.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMinWindow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinWindowMouseClicked(evt);
            }
        });

        jlabelCloseWin1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlabelCloseWin1.setForeground(new java.awt.Color(250, 250, 250));
        jlabelCloseWin1.setText("X");
        jlabelCloseWin1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlabelCloseWin1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlabelCloseWin1MouseClicked(evt);
            }
        });

        jLabelMinWindow1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelMinWindow1.setForeground(new java.awt.Color(250, 250, 250));
        jLabelMinWindow1.setText("-");
        jLabelMinWindow1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMinWindow1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinWindow1MouseClicked(evt);
            }
        });

        jlabelCloseWin2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlabelCloseWin2.setForeground(new java.awt.Color(250, 250, 250));
        jlabelCloseWin2.setText("X");
        jlabelCloseWin2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabelMinWindow2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelMinWindow2.setForeground(new java.awt.Color(250, 250, 250));
        jLabelMinWindow2.setText("-");
        jLabelMinWindow2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jlabelCloseWin3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlabelCloseWin3.setForeground(new java.awt.Color(250, 250, 250));
        jlabelCloseWin3.setText("X");
        jlabelCloseWin3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlabelCloseWin3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlabelCloseWin3MouseClicked(evt);
            }
        });

        jLabelMinWindow3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelMinWindow3.setForeground(new java.awt.Color(250, 250, 250));
        jLabelMinWindow3.setText("-");
        jLabelMinWindow3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMinWindow3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinWindow3MouseClicked(evt);
            }
        });

        jLabelTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(250, 250, 250));
        jLabelTitle.setText("Car Diagnostic");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(92, 151, 191));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(250, 250, 250));
        jLabel8.setText("X");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(250, 250, 250));
        jLabel9.setText("-");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(250, 250, 250));
        jLabel10.setText("Car Diagnostic");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(27, 27, 27)
                .addComponent(jLabel8)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(52, 73, 94));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(250, 250, 250));
        jLabel1.setText("Look up a Query");

        jPanel3.setBackground(new java.awt.Color(52, 73, 94));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(250, 250, 250));
        jLabel2.setText("Please Enter your Vehicle's Details:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(250, 250, 250));
        jLabel3.setText("VIN #");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(250, 250, 250));
        jLabel4.setText("DTC code");

        jTextFieldDTC.setBackground(new java.awt.Color(232, 236, 241));
        jTextFieldDTC.setText("p0420");
        jTextFieldDTC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDTCActionPerformed(evt);
            }
        });

        jTextFieldMileage.setBackground(new java.awt.Color(232, 236, 241));
        jTextFieldMileage.setText("51000");
        jTextFieldMileage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMileageActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(250, 250, 250));
        jLabel5.setText("Mileage");
        jLabel5.setToolTipText("");

        jTextFieldVin.setBackground(new java.awt.Color(232, 236, 241));
        jTextFieldVin.setText("1GNALDEK9FZ108495");
        jTextFieldVin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldVinActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(69, 69, 69)
                        .addComponent(jTextFieldVin))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 140, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldDTC)
                            .addComponent(jTextFieldMileage))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldVin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(50, 50, 50)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldMileage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(47, 47, 47)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDTC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(23, 23, 23))
        );

        jButtonEnter.setText("Enter Query");
        jButtonEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnterActionPerformed(evt);
            }
        });

        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(250, 250, 250));
        jLabel7.setText("Diagnosis:");

        jTextAreaDiagnosis.setColumns(20);
        jTextAreaDiagnosis.setRows(5);
        jScrollPane2.setViewportView(jTextAreaDiagnosis);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jButtonCancel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonEnter)
                .addGap(51, 51, 51))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(318, 318, 318))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(281, 281, 281))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEnter)
                    .addComponent(jButtonCancel))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldDTCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDTCActionPerformed

    }//GEN-LAST:event_jTextFieldDTCActionPerformed

    private void jTextFieldMileageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMileageActionPerformed

    }//GEN-LAST:event_jTextFieldMileageActionPerformed

    private void jButtonEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnterActionPerformed
        String _dtc, _vin;
        int _mileage;

        /*
        PrintStream printStream = new PrintStream(new CustomOutputStream(jTextAreaDiagnosis));
        System.setOut(printStream);
        System.setErr(printStream);

        */
       _mileage = Integer.parseInt(jTextFieldMileage.getText());
        _dtc = jTextFieldDTC.getText();
        _vin = jTextFieldVin.getText();

       api.CarDiagApi interpreter = new api.CarDiagApi();
       interpreter.loadDiagnostic(_vin, _mileage, _dtc);
       //jTextAreaDiagnosis.append();

    }//GEN-LAST:event_jButtonEnterActionPerformed

    private void jlabelCloseWinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabelCloseWinMouseClicked
        //Close window
        System.exit(0);
    }//GEN-LAST:event_jlabelCloseWinMouseClicked

    private void jLabelMinWindowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinWindowMouseClicked
        //Minimize window
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelMinWindowMouseClicked

    private void jlabelCloseWin1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabelCloseWin1MouseClicked
        //Closes window
        System.exit(0);
    }//GEN-LAST:event_jlabelCloseWin1MouseClicked

    private void jLabelMinWindow1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinWindow1MouseClicked
        //Minimizes window
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelMinWindow1MouseClicked

    private void jlabelCloseWin3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabelCloseWin3MouseClicked
        //Closes window
        System.exit(0);
    }//GEN-LAST:event_jlabelCloseWin3MouseClicked

    private void jLabelMinWindow3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinWindow3MouseClicked
        //Minimizes window
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelMinWindow3MouseClicked

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        // disposes of window
        dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jTextFieldVinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldVinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldVinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterpreterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterpreterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterpreterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterpreterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterpreterForm().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonEnter;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelMinWindow;
    private javax.swing.JLabel jLabelMinWindow1;
    private javax.swing.JLabel jLabelMinWindow2;
    private javax.swing.JLabel jLabelMinWindow3;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaDiagnosis;
    private javax.swing.JTextField jTextFieldDTC;
    private javax.swing.JTextField jTextFieldMileage;
    private javax.swing.JTextField jTextFieldVin;
    private javax.swing.JLabel jlabelCloseWin;
    private javax.swing.JLabel jlabelCloseWin1;
    private javax.swing.JLabel jlabelCloseWin2;
    private javax.swing.JLabel jlabelCloseWin3;
    // End of variables declaration//GEN-END:variables
}
